name: riverpod_weather
description: "A simple example on how to use riverpod with some clean architecture"
version: 1.1.0+2
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_use: ^0.0.4
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.3
  stack_trace: ^1.11.1
  talker_dio_logger: ^2.4.0
  talker_flutter: ^3.6.0

dependency_overrides:
  analyzer: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_gen: ^5.3.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  very_good_analysis: ^5.1.0

assets:
  - .env.json

flutter:
  uses-material-design: true
  generate: true
